### ISSUE TITLE
email.gs example throws error

### ISSUE THREAD

**Issue by rampall** [jcubic/gaiman#89]
![image](https://user-images.githubusercontent.com/520570/195835976-92987631-85d3-4eb7-9b11-eeac44b1f61a.png)

**Comment by jcubic** [comment]
Thanks for taking the time to check this and report. Will fix this after the weekend.

The problem is that:
```ruby
prompt_email()
```

is compiled into wrong syntax:

```javascript
gaiman.prompt();
await $__email();
```

**Comment by jcubic** [comment]
The code is fixed. Now it properly parses all functions that have static commands as part of the name.
