### ISSUE TITLE
jQuery Terminal how to change text color to white?

### ISSUE THREAD

**Issue by bitcoinmeetups** [jcubic/gaiman#92]
Hi jcubic,

I'm BM, a very nice and polite guy.

In your terminal example below, is there an easy way to switch text color from green to white?

I don't have a link to the github for that project so I'm asking here. Also checking out gaiman.

https://itnext.io/how-to-create-interactive-terminal-like-website-888bb0972288

**Comment by jcubic** [comment]
The repo for jQuery Terminal is here: [jcubic/jquery.terminal](https://github.com/jcubic/jquery.terminal).

And the documentation about styling can be found on a Wiki [CSS-Style](https://github.com/jcubic/jquery.terminal/wiki/CSS-Style).

But which example do you talk about? The default example has gray color on black. Are you talking about Vintage demo on CodePen?

**Comment by bitcoinmeetups** [comment]
Ah, got it. Feel free to move this issue to the jquery.terminal repo instead. I will check the CSS-Style link. 

And I'm using a black and white screen. I was assuming that in your example which I think I found on medium, the text color was green but it may be gray indeed. Can't really see it on this b/w screen, so I need to switch it to white and increase font size a bit.

**Comment by jcubic** [comment]
I will close. You can't actually move issues between repositories. If you want, you can ask again in the proper one.

**Comment by jcubic** [comment]
IF you want the color white and font bigger use:
```css
:root {
   --size: 1.4;
   --color: white;
}
```
